version: '3'

services:
    openresty:
        container_name: openresty
        build: ./
        ports:
            - "80:80"
        restart: always
        volumes:
            - "./openresty/config/conf.d:/usr/local/openresty/nginx/conf.d:rw"
            - "./openresty/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw"