version: '3'

services:
    openresty:
        container_name: openresty
        build: ./openresty
        ports:
            - "80:80"
        volumes: 
            - "./openresty/config/vhosts/:/etc/nginx/conf.d:rw"
        restart: always
